In [2]:
import tensorflow as tf
#텐서 플로우 사용시 임포트 필수

tensor = tf.constant(3)
#기본 텐서 만들기

print(tensor)

#텐서가 필요한 이유
#행렬로 인풋/w값 저장 가능 -> node 계산식이 쉬어진

tf.Tensor(3, shape=(), dtype=int32)


In [3]:
tensor2 = tf.constant([3,4,5])
tensor3 = tf.constant([6,7,8])
#숫자를 한번에 계산
print(tensor2+tensor3)

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [5]:
tensor4 = tf.constant([[1,2], [3,4]])
#행렬처럼 표현

print(tf.add(tensor2,tensor3))
#함수를 이용한 더하기
#subtract 빼기, divide 나누기, multiply 곱하기
#matmul : 행렬의 곱 연산

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [10]:
tensor5=tf.zeros(10)
#0만 담긴 텐서 만들어줌
tensor6=tf.zeros([2,2])
tensor7=tf.zeros([2,2,3])

print(tensor5)
print(tensor6)
print(tensor7)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)


In [11]:
tensor6.shape
#텐서 몇행 몇열인지 알려줌
#shape => 차원

TensorShape([2, 2])

In [12]:
#tensor의 datatype
print(tensor6)

#주로 실수로 표현해서 데이터 넣을 시에 float 형으로 넣는게 좋음

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [15]:
w= tf.Variable(1.0)
#weigh 같은 경우 Variable로 설정해야함 : 변경 가능한 값
print(w)
w.assign(2)
#값 변경
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>


In [19]:
#간단한 수학 문제
키 = 170
신발 = 260

#신발 = 키 * a + b

a= tf.Variable(0.1)
b= tf.Variable(0.2)

opt= tf.keras.optimizers.Adam(learning_rate=0.1)
#경사하강법을 도와주는 친구(keras.optimizers)

#opt.minimize(손실함수, var_list=[a,b])
#var_list => 경사하강법으로 업데이트할 weight Variable 목록
#손실 함수 => 실제값 - 예측값 => 오차

def 손실함수():
    예측값 = 키 * a- b
    return tf.square(260- 예측값)
    #square : 제곱해주는 함수
#opt.minimize(손실함수, var_list=[a,b])
# 경사하강 1번 해줌

for i in range(300):
    opt.minimize(손실함수, var_list=[a,b])
    #반복시킴
    print(a.numpy(), b.numpy())
    

0.2 0.1
0.2997435 0.00025648624
0.39903066 -0.099030666
0.49763417 -0.19763419
0.59530145 -0.2953015
0.6917507 -0.39175075
0.7866689 -0.48666897
0.8797134 -0.5797135
0.97051114 -0.67051125
1.0586612 -0.7586613
1.1437385 -0.84373856
1.2252998 -0.9252998
1.3028927 -1.0028927
1.3760661 -1.0760661
1.444384 -1.1443839
1.5074394 -1.2074393
1.5648708 -1.2648706
1.6163764 -1.3163761
1.6617273 -1.361727
1.7007784 -1.400778
1.7334735 -1.4334732
1.7598486 -1.4598483
1.7800286 -1.4800283
1.7942222 -1.4942219
1.8027135 -1.5027132
1.8058512 -1.5058509
1.8040382 -1.5040379
1.79772 -1.4977196
1.7873744 -1.4873741
1.7735018 -1.4735014
1.7566158 -1.4566154
1.7372359 -1.4372356
1.7158803 -1.41588
1.6930588 -1.3930585
1.6692679 -1.3692676
1.6449842 -1.3449839
1.6206602 -1.3206599
1.5967184 -1.2967181
1.5735475 -1.2735472
1.5514976 -1.2514973
1.5308766 -1.2308763
1.5119475 -1.2119472
1.4949255 -1.1949252
1.4799768 -1.1799765
1.4672182 -1.1672179
1.4567174 -1.1567171
1.4484947 -1.1484944
1.4425253 -1.142525

In [5]:
#대학원 합격 확률 구하기
import pandas as pd
#엑셀 데이터를 다룰때 사용

data= pd.read_csv('gpascore.csv')

data=data.dropna()
#pandas 사용은 아랫 칸 참조

y데이터 = data['admit'].values
#values -> 해당 값을 리스트로 담아줌
x데이터 = []

for i, rows in data.iterrows():
    #iterrows 함수: data라는 데이터 프레임을 가로 한줄씩 출력
    x데이터.append([rows['gre'], rows['gpa'], rows['rank']])

#일반 리스트를 numpy array로 변환해야 tensorflow에 집어 넣기 가능
import numpy as np
#numpy -> 다차원 리스트, 행렬 만들때 사용

    
import tensorflow as tf
#keras : w값 찾거나 할때 유용한 도구
model= tf.keras.models.Sequential([tf.keras.layers.Dense(64,activation='tanh'),tf.keras.layers.Dense(128,activation='tanh'),tf.keras.layers.Dense(1,activation='sigmoid')]) #딥러닝 모델
#tf.keras.layers.Dense(node 갯수,activation 함수) 기본적인 히든 레이어 만드는 법
#노드 갯수의 경우 숫자 상관없음 but 2에 제곱수로 많이 함, 마지막은 신경써서 해야함(결과) 결과는정수로 잘 안나옴

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
#optimizer -> 경사 하강법할때, 얼마나 빼줄지(러닝메이트) => Adam 많이씀
#loss -> 손실 함수 => binary_crossentropy확률 계산할때 좋음
#metrics -> 어떤 요소로 평가 할지

model.fit(np.array(x데이터), np.array(y데이터), epochs=1000)
#모델 학습시키기
#model.fit(x데이터, y 데이터, epochs=10)
#x 데이터는 학습데이터, y데이터는 실제 정답 epo 학습시킬 횟수


#예측
예측값=model.predict([[750,3.70,3],[400,2.2,1]])
#모델을 통해서 예측해주는 함수
print(예측값)


Epoch 1/1000
14/14 [==============================] - 1s 2ms/step - loss: 0.7179 - accuracy: 0.4871
Epoch 2/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.7142 - accuracy: 0.4729
Epoch 3/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6973 - accuracy: 0.4847
Epoch 4/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6901 - accuracy: 0.5318
Epoch 5/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.7183 - accuracy: 0.4847
Epoch 6/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.7028 - accuracy: 0.4988
Epoch 7/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6836 - accuracy: 0.5459
Epoch 8/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6806 - accuracy: 0.6165
Epoch 9/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6872 - accuracy: 0.5200
Epoch 10/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6716 - accuracy: 0.5741

14/14 [==============================] - 0s 1ms/step - loss: 0.6473 - accuracy: 0.6000
Epoch 83/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6238 - accuracy: 0.6729
Epoch 84/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6638 - accuracy: 0.6141
Epoch 85/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6327 - accuracy: 0.6494
Epoch 86/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6315 - accuracy: 0.6424
Epoch 87/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6418 - accuracy: 0.6376
Epoch 88/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6385 - accuracy: 0.6329
Epoch 89/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6474 - accuracy: 0.6494
Epoch 90/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6837 - accuracy: 0.5412
Epoch 91/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6650 - accuracy: 0.5624
Epoc

14/14 [==============================] - 0s 2ms/step - loss: 0.6430 - accuracy: 0.6212
Epoch 163/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6393 - accuracy: 0.6235
Epoch 164/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6332 - accuracy: 0.6376
Epoch 165/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6358 - accuracy: 0.6376
Epoch 166/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6322 - accuracy: 0.6188
Epoch 167/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6567 - accuracy: 0.6376
Epoch 168/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6811 - accuracy: 0.5718
Epoch 169/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6656 - accuracy: 0.5788
Epoch 170/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6316 - accuracy: 0.6329
Epoch 171/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6309 - accuracy: 0.

14/14 [==============================] - 0s 2ms/step - loss: 0.6407 - accuracy: 0.6353
Epoch 243/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6267 - accuracy: 0.6588
Epoch 244/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6188 - accuracy: 0.6541
Epoch 245/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6355 - accuracy: 0.6376
Epoch 246/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6536 - accuracy: 0.6235
Epoch 247/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6306 - accuracy: 0.6376
Epoch 248/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6434 - accuracy: 0.6259
Epoch 249/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6346 - accuracy: 0.6612
Epoch 250/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6345 - accuracy: 0.6259
Epoch 251/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6214 - accuracy: 0.

14/14 [==============================] - 0s 3ms/step - loss: 0.6405 - accuracy: 0.6282
Epoch 323/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6617 - accuracy: 0.5882
Epoch 324/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6284 - accuracy: 0.6494
Epoch 325/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6144 - accuracy: 0.6612
Epoch 326/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6140 - accuracy: 0.6682
Epoch 327/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6436 - accuracy: 0.6329
Epoch 328/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6321 - accuracy: 0.6165
Epoch 329/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6204 - accuracy: 0.6518
Epoch 330/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6247 - accuracy: 0.6447
Epoch 331/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6532 - accuracy: 0.

14/14 [==============================] - 0s 2ms/step - loss: 0.6054 - accuracy: 0.6706
Epoch 403/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6170 - accuracy: 0.6729
Epoch 404/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6065 - accuracy: 0.6612
Epoch 405/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6038 - accuracy: 0.6729
Epoch 406/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6244 - accuracy: 0.6541
Epoch 407/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6352 - accuracy: 0.6376
Epoch 408/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6268 - accuracy: 0.6494
Epoch 409/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5991 - accuracy: 0.6565
Epoch 410/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6080 - accuracy: 0.6682
Epoch 411/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6159 - accuracy: 0.

14/14 [==============================] - 0s 2ms/step - loss: 0.5955 - accuracy: 0.6871
Epoch 483/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6002 - accuracy: 0.6800
Epoch 484/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6154 - accuracy: 0.6659
Epoch 485/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5958 - accuracy: 0.6776
Epoch 486/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6162 - accuracy: 0.6588
Epoch 487/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6123 - accuracy: 0.6776
Epoch 488/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5978 - accuracy: 0.6918
Epoch 489/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6064 - accuracy: 0.6659
Epoch 490/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5906 - accuracy: 0.6988
Epoch 491/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6051 - accuracy: 0.

14/14 [==============================] - 0s 2ms/step - loss: 0.6182 - accuracy: 0.6706
Epoch 563/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6030 - accuracy: 0.6776
Epoch 564/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.5919 - accuracy: 0.6941
Epoch 565/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5813 - accuracy: 0.7035
Epoch 566/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5987 - accuracy: 0.6729
Epoch 567/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5726 - accuracy: 0.7012
Epoch 568/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5870 - accuracy: 0.6894
Epoch 569/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6365 - accuracy: 0.6447
Epoch 570/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5847 - accuracy: 0.6941
Epoch 571/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5921 - accuracy: 0.

14/14 [==============================] - 0s 1ms/step - loss: 0.6070 - accuracy: 0.6729
Epoch 643/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.5699 - accuracy: 0.6965
Epoch 644/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5899 - accuracy: 0.6965
Epoch 645/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5811 - accuracy: 0.6706
Epoch 646/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5651 - accuracy: 0.7035
Epoch 647/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6169 - accuracy: 0.6424
Epoch 648/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6064 - accuracy: 0.6565
Epoch 649/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6192 - accuracy: 0.6518
Epoch 650/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5992 - accuracy: 0.6729
Epoch 651/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5643 - accuracy: 0.

14/14 [==============================] - 0s 2ms/step - loss: 0.5697 - accuracy: 0.6965
Epoch 723/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5681 - accuracy: 0.7012
Epoch 724/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5414 - accuracy: 0.7271
Epoch 725/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5543 - accuracy: 0.7200
Epoch 726/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5365 - accuracy: 0.7176
Epoch 727/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5589 - accuracy: 0.7153
Epoch 728/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6069 - accuracy: 0.6753
Epoch 729/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5600 - accuracy: 0.7153
Epoch 730/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5394 - accuracy: 0.7318
Epoch 731/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5727 - accuracy: 0.

14/14 [==============================] - 0s 3ms/step - loss: 0.5472 - accuracy: 0.7106
Epoch 803/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5179 - accuracy: 0.7435
Epoch 804/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.5647 - accuracy: 0.7176
Epoch 805/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6920 - accuracy: 0.6188
Epoch 806/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5961 - accuracy: 0.6894
Epoch 807/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5495 - accuracy: 0.7529
Epoch 808/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5332 - accuracy: 0.7482
Epoch 809/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5341 - accuracy: 0.7341
Epoch 810/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5787 - accuracy: 0.6894
Epoch 811/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5809 - accuracy: 0.

14/14 [==============================] - 0s 2ms/step - loss: 0.5185 - accuracy: 0.7576
Epoch 883/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5124 - accuracy: 0.7506
Epoch 884/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5112 - accuracy: 0.7694
Epoch 885/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5307 - accuracy: 0.7365
Epoch 886/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5586 - accuracy: 0.7176
Epoch 887/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5361 - accuracy: 0.7365
Epoch 888/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5198 - accuracy: 0.7435
Epoch 889/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.5220 - accuracy: 0.7553
Epoch 890/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5393 - accuracy: 0.7529
Epoch 891/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5107 - accuracy: 0.

14/14 [==============================] - 0s 2ms/step - loss: 0.5080 - accuracy: 0.7365
Epoch 963/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.5003 - accuracy: 0.7812
Epoch 964/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.4949 - accuracy: 0.7835
Epoch 965/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.5004 - accuracy: 0.7694
Epoch 966/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6007 - accuracy: 0.6800
Epoch 967/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.5411 - accuracy: 0.7365
Epoch 968/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5095 - accuracy: 0.7459
Epoch 969/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5254 - accuracy: 0.7365
Epoch 970/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5150 - accuracy: 0.7647
Epoch 971/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.4917 - accuracy: 0.

In [6]:
import pandas as pd
#엑셀 데이터를 다룰때 사용

data= pd.read_csv('gpascore.csv')
#print(data)
#pandas를 이용한 데이터 전처리
print(data.isnull().sum())
#빈칸인 데이터 찾기
data.dropna()
#빈칸인 데이터 없애기
print(data.isnull().sum())

#data.fillna(값) : 빈칸을 값으로 변경해줌

#data['세로줄'] -> 원하는 줄에 값 모두 출력 가능 => .min() -> 최소값 출력 max 최댓값, .count 갯수


admit    0
gre      1
gpa      0
rank     0
dtype: int64
admit    0
gre      1
gpa      0
rank     0
dtype: int64
